export const plans  = [
    {
        "id": 1,
        "name": "daily",
        'duration': '1',
        "date": 'oct-23-2024',
        "discount": 'False',
        "percent": 'N/A',
        "status": 'Active',
    },
    {
        "id": 2,
        "name": "Monthly",
        'duration': '1',
        "date": 'oct-23-2024',
        "discount": 'True',
        "percent": '2%',
        "status": 'Active',
    },
    {
        "id": 3,
        "name": "Monthly",
        "duration": '3', 
        "date": 'oct-23-2024',
        "discount": 'True',
        "percent": '5%',
        "status": 'Active',
    },
    {
        "id": 4,
        "name": "Monthly",
        "duration": 6, 
        "date": 'oct-23-2024',
        "discount": 'True',
        "percent": '10%',
        "status": 'Active',
    },
    {
        "id": 4,
        "name": "Monthly",
        "duration": 6, 
        "date": 'oct-23-2024',
        "discount": 'True',
        "percent": '10%',
        "status": 'Active',
    },
   
]